# PostgreSQL service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: airflow
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
---
# PostgreSQL deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: airflow
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13
          env:
            - name: POSTGRES_USER
              value: airflow
            - name: POSTGRES_PASSWORD
              value: airflow
            - name: POSTGRES_DB
              value: airflow
          ports:
            - containerPort: 5432
---
# Airflow webserver service
apiVersion: v1
kind: Service
metadata:
  name: airflow-service
  namespace: airflow
spec:
  type: NodePort
  selector:
    app: airflow
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
---
# Airflow deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-deployment
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
  template:
    metadata:
      labels:
        app: airflow
    spec:
      containers:
        - name: airflow
          image: apache/airflow:2.8.2
          ports:
            - containerPort: 8080
          env:
            - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
              value: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
          volumeMounts:
            - name: airflow-dags-volume
              mountPath: /opt/airflow/dags
          command: [ "bash", "-c" ]
          args:
            - |
              airflow db init && \
              airflow db upgrade && \
              airflow users create \
                --username admin \
                --firstname Admin \
                --lastname User \
                --role Admin \
                --email jwillekes@xccelerated.io \
                --password admin || true && \
              airflow scheduler & \
              exec airflow webserver
      volumes:
        - name: airflow-dags-volume
          hostPath:
            path: /Users/jellewillekes/airflow_deployment/dags
            type: Directory
